# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.7.1/charts/other/app-template/values.schema.json
app-template:
  defaultPodOptions:
    enableServiceLinks: false
  controllers:
    webtop:
      strategy: Recreate
      containers:
        webtop:
          image:
            repository: lscr.io/linuxserver/webtop
            tag: ubuntu-xfce
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Asia/Shanghai
            - name: CUSTOM_USER
              value: casey
            - name: START_DOCKER
              value: "false"
            - name: DOCKER_MODS
              value: linuxserver/mods:universal-package-install
            - name: INSTALL_PACKAGES
              value: fonts-noto-cjk|git|vim
            - name: LC_ALL
              value: zh_CN.UTF-8
            # https://github.com/linuxserver/docker-webtop/blob/master/README.md
            - name: PIXELFLUX_WAYLAND
              value: "true"
            - name: AUTO_GPU
              value: "true"
            - name: SELKIES_MANUAL_WIDTH
              value: "1920"
            - name: SELKIES_MANUAL_HEIGHT
              value: "1080"
            - name: MAX_RESOLUTION
              value: "1920x1080"
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 100m
              memory: 3471Mi
            limits:
              memory: 4666Mi
  service:
    webtop:
      controller: webtop
      ports:
        http:
          port: 3000
          protocol: TCP
        https:
          # https://tailscale.com/docs/features/kubernetes-operator/how-to/cluster-ingress#exposing-cluster-workloads-using-a-kubernetes-ingress
          port: 443
          protocol: TCP
          targetPort: 3001
  ingress:
    webtop:
      enabled: true
      className: tailscale
      annotations:
        tailscale.com/proxy-group: ingress-proxies
      defaultBackend:
        service:
          name: webtop
          port:
            name: https
      tls:
        - hosts:
            - webtop.west-beta.ts.net
  persistence:
    config:
      suffix: config
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 100Gi
      retain: true
      globalMounts:
        - path: /config
    dri-devices:
      enabled: true
      type: hostPath
      hostPath: /dev/dri
      globalMounts:
        - path: /dev/dri
          readOnly: false
    shm-volume:
      enabled: true
      type: emptyDir
      medium: Memory
      sizeLimit: 2Gi
      globalMounts:
        - path: /dev/shm
          readOnly: false
