# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.7.1/charts/other/app-template/values.schema.json
app-template:
  defaultPodOptions:
    enableServiceLinks: true
  controllers:
    webtop:
      strategy: Recreate
      containers:
        webtop:
          image:
            repository: lscr.io/linuxserver/webtop
            tag: ubuntu-xfce
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Asia/Shanghai
            - name: CUSTOM_USER
              value: casey
            - name: START_DOCKER
              value: "false"
            - name: DOCKER_MODS
              value: linuxserver/mods:universal-package-install
            - name: INSTALL_PACKAGES
              value: fonts-noto-cjk|git|vim
            - name: LC_ALL
              value: zh_CN.UTF-8
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 100m
              memory: 4666Mi
            limits:
              memory: 4666Mi
  service:
    webtop:
      controller: webtop
      ports:
        http:
          port: 3000
          protocol: TCP
  ingress:
    webtop:
      enabled: true
      className: tailscale
      hosts:
        - host: &host webtop.west-beta.ts.net
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: webtop
                port: http
      tls:
        - hosts:
            - *host
  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 100Gi
      retain: true
      globalMounts:
        - path: /config
    dri-devices:
      enabled: true
      type: hostPath
      hostPath: /dev/dri
      globalMounts:
        - path: /dev/dri
          readOnly: false
    shm-volume:
      enabled: true
      type: emptyDir
      medium: Memory
      sizeLimit: 2Gi
      globalMounts:
        - path: /dev/shm
          readOnly: false
