apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/part-of: rsshub
    io.kompose.service: redis-data
  name: redis-data
  namespace: rsshub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
