apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: database-postgres
  name: database-postgres-np
  namespace: rsshub
spec:
  ports:
    - name: "5432"
      nodePort: 30723
      port: 5432
  selector:
    io.kompose.service: database-postgres
  type: NodePort
