eraser:
  runtimeConfig:
    manager:
      runtime:
        name: containerd
        address: unix:///run/k3s/containerd/containerd.sock
    components:
      scanner:
        request:
          cpu: 10m
  deploy:
    resources:
      limits:
        memory: 30Mi
      requests:
        cpu: 1m
        memory: 30Mi
