apiVersion: v2
name: kube-prometheus-stack
version: 0.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 89.1.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: prometheus-smartctl-exporter
    version: 0.17.1
    repository: https://prometheus-community.github.io/helm-charts
