services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: netbootxyz
    volumes:
      - ./data/netbootxyz-config/root/etc/supervisor.conf:/etc/supervisor.conf
      - ./data/netbootxyz-config/root/etc/dnsmasq.conf:/etc/dnsmasq.conf
      - ./data/netbootxyz-config/config:/config
      - ./data/netbootxyz-config/assets:/assets
      - ./data/iso:/assets/iso
      - ./data/init-config:/assets/init-config
    network_mode: host
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
