apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: database-postgres-claim0
  name: database-postgres-claim0
  namespace: rsshub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
