{
 "title": "Kor Dashboard",
 "description": "A Dashboard to view unused resources in Kubernetes",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kubernetes_orphaned_resources,exported_namespace)"
    }
   },
   {
    "name": "kind",
    "query": {
     "query": "label_values(kubernetes_orphaned_resources,kind)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Unused Resources Sum (Namespace)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(exported_namespace) (kubernetes_orphaned_resources{kind=~\"$kind\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Unused Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Unused Resources Pie (Kind)",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubernetes_orphaned_resources{exported_namespace=~\"$namespace\", kind=~\"$kind\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unused Resources Bar (Kind)",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kubernetes_orphaned_resources{exported_namespace=~\"$namespace\", kind=~\"$kind\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unused $kind",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 37 },
   "repeat": "kind",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubernetes_orphaned_resources{exported_namespace=~\"$namespace\", kind=~\"$kind\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}