apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr
  namespace: {{ .Release.Namespace }}
  annotations:
    tailscale.com/proxy-group: ingress-proxies
spec:
  defaultBackend:
    service:
      name: jellyfin
      port:
        name: prowlarr
  ingressClassName: tailscale
  tls:
    - hosts:
        - prowlarr.west-beta.ts.net
