apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transmission
  namespace: {{ .Release.Namespace }}
  annotations:
    tailscale.com/proxy-group: ingress-proxies
spec:
  defaultBackend:
    service:
      name: jellyfin
      port:
        name: transmission
  ingressClassName: tailscale
  tls:
    - hosts:
        - transmission.west-beta.ts.net
