kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-anothervideos
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: pv-nfs-anothervideos
  storageClassName: nfs-csi-anothervideos
