kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-thirdvideos
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: pv-nfs-thirdvideos
  storageClassName: nfs-csi-thirdvideos
