apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    tailscale.com/experimental-forward-cluster-traffic-via-ingress: "true"
    tailscale.com/proxy-group: ingress-proxies
  name: lobe
spec:
  ingressClassName: tailscale
  rules:
    - host: lobe
      http:
        paths:
          - backend:
              service:
                name: lobe
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - lobe
