apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: lobe.west-beta.ts.net
    tailscale.com/proxy-group: egress-proxies
  name: egress-lobe
spec:
  externalName: unused
  type: ExternalName
  ports:
    - port: 443
      protocol: TCP
      name: https
