rook-ceph:
  monitoring:
    enabled: true
  csi:
    serviceMonitor:
      enabled: true
  enableDiscoveryDaemon: true
rook-ceph-cluster:
  monitoring:
    enabled: true
    createPrometheusRules: true
  cephClusterSpec:
    mon:
      count: 3
    mgr:
      count: 2
      modules:
        - name: rook
          enabled: true
        # Rook mgr module crashes due to missing mgr.nfs
        - name: nfs
          enabled: false
    dashboard:
      enabled: true
      ssl: false
    logCollector:
      enabled: false
    removeOSDsIfOutAndSafeToRemove: true
    resources:
      mgr:
        limits:
          memory: 1093Mi
        requests:
          cpu: 7m
          memory: 584Mi
      mon:
        limits:
          memory: 1451Mi
        requests:
          cpu: 15m
          memory: 1164Mi
      osd:
        limits:
          memory: 2264Mi
        requests:
          cpu: 75m
          memory: 2083Mi
  cephBlockPools:
    - name: standard-rwo
      spec:
        replicated:
          size: 2
      storageClass:
        enabled: true
        name: standard-rwo
        isDefault: true
        allowVolumeExpansion: true
        parameters:
          imageFeatures: layering,fast-diff,object-map,deep-flatten,exclusive-lock
          csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
          csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
          csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
          csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
  cephBlockPoolsVolumeSnapshotClass:
    enabled: true
    isDefault: true
  cephFileSystems:
    - name: standard-rwx
      spec:
        metadataPool:
          replicated:
            size: 2
        dataPools:
          - name: data0
            replicated:
              size: 2
        metadataServer:
          activeCount: 1
          activeStandby: true
          resources:
            limits:
              memory: 71Mi
            requests:
              cpu: 10m
              memory: 67Mi
          priorityClassName: system-cluster-critical
      storageClass:
        enabled: true
        name: standard-rwx
        isDefault: false
        allowVolumeExpansion: true
        pool: data0
        parameters:
          csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
          csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
          csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
          csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
  cephFileSystemVolumeSnapshotClass:
    enabled: true
    isDefault: false
  cephObjectStores: []
  ingress:
    dashboard:
      host:
        name: rook-ceph-dashboard.west-beta.ts.net
        path: "/"
      tls:
        - hosts:
            - rook-ceph-dashboard.west-beta.ts.net
      ingressClassName: tailscale
  toolbox:
    enabled: true
