rook-ceph:
  monitoring:
    enabled: true
  csi:
    serviceMonitor:
      enabled: true
    csiRBDProvisionerResource: |
      - name : csi-provisioner
        resource:
          requests:
            cpu: 2m
            memory: 44Mi
          limits:
            memory: 88Mi
      - name : csi-resizer
        resource:
          requests:
            cpu: 3m
            memory: 34Mi
          limits:
            memory: 68Mi
      - name : csi-attacher
        resource:
          requests:
            cpu: 2m
            memory: 44Mi
          limits:
            memory: 88Mi
      - name : csi-snapshotter
        resource:
          requests:
            cpu: 1m
            memory: 28Mi
          limits:
            memory: 56Mi
      - name : csi-rbdplugin
        resource:
          requests:
            memory: 128Mi
            cpu: 2m
          limits:
            memory: 256Mi
      - name : csi-omap-generator
        resource:
          requests:
            memory: 256Mi
            cpu: 2m
          limits:
            memory: 512Mi
      - name : liveness-prometheus
        resource:
          requests:
            memory: 42Mi
            cpu: 1m
          limits:
            memory: 84Mi
    # -- CEPH CSI RBD plugin resource requirement list
    # @default -- see values.yaml
    csiRBDPluginResource: |
      - name : driver-registrar
        resource:
          requests:
            cpu: 2m
            memory: 42Mi
          limits:
            memory: 84Mi
      - name : csi-rbdplugin
        resource:
          requests:
            memory: 128Mi
            cpu: 2m
          limits:
            memory: 256Mi
      - name : liveness-prometheus
        resource:
          requests:
            memory: 42Mi
            cpu: 1m
          limits:
            memory: 84Mi

    # -- CEPH CSI CephFS provisioner resource requirement list
    # @default -- see values.yaml
    csiCephFSProvisionerResource: |
      - name : csi-provisioner
        resource:
          requests:
            cpu: 2m
            memory: 42Mi
          limits:
            memory: 84Mi
      - name : csi-resizer
        resource:
          requests:
            cpu: 3m
            memory: 17Mi
          limits:
            memory: 34Mi
      - name : csi-attacher
        resource:
          requests:
            cpu: 1m
            memory: 13Mi
          limits:
            memory: 26Mi
      - name : csi-snapshotter
        resource:
          requests:
            cpu: 1m
            memory: 40Mi
          limits:
            memory: 80Mi
      - name : csi-cephfsplugin
        resource:
          requests:
            cpu: 1m
            memory: 24Mi
          limits:
            memory: 48Mi
      - name : liveness-prometheus
        resource:
          requests:
            memory: 32Mi
            cpu: 1m
          limits:
            memory: 64Mi

    # -- CEPH CSI CephFS plugin resource requirement list
    # @default -- see values.yaml
    csiCephFSPluginResource: |
      - name : driver-registrar
        requests:
          cpu: 1m
          memory: 10Mi
        limits:
          memory: 20Mi
      - name : csi-cephfsplugin
        resource:
          requests:
            cpu: 1m
            memory: 21Mi
          limits:
            memory: 42Mi
      - name : liveness-prometheus
        resource:
          requests:
            memory: 32Mi
            cpu: 1m
          limits:
            memory: 64Mi

  enableDiscoveryDaemon: true
rook-ceph-cluster:
  monitoring:
    enabled: true
    createPrometheusRules: true
  cephClusterSpec:
    mon:
      count: 3
    mgr:
      count: 2
      modules:
        - name: rook
          enabled: true
        # Rook mgr module crashes due to missing mgr.nfs
        - name: nfs
          enabled: false
    dashboard:
      enabled: true
      ssl: false
    logCollector:
      enabled: false
    removeOSDsIfOutAndSafeToRemove: true
    resources:
      mgr:
        limits:
          memory: 1093Mi
        requests:
          cpu: 7m
          memory: 584Mi
      mon:
        limits:
          memory: 1451Mi
        requests:
          cpu: 15m
          memory: 559Mi
      osd:
        limits:
          memory: 2264Mi
        requests:
          cpu: 75m
          memory: 1500Mi
  cephBlockPools:
    - name: standard-rwo
      spec:
        replicated:
          size: 2
      storageClass:
        enabled: true
        name: standard-rwo
        isDefault: true
        allowVolumeExpansion: true
        parameters:
          imageFeatures: layering,fast-diff,object-map,deep-flatten,exclusive-lock
          csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
          csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
          csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
          csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
  cephBlockPoolsVolumeSnapshotClass:
    enabled: true
    isDefault: true
  cephFileSystems:
    - name: standard-rwx
      spec:
        metadataPool:
          replicated:
            size: 2
        dataPools:
          - name: data0
            replicated:
              size: 2
        metadataServer:
          activeCount: 1
          activeStandby: true
          resources:
            limits:
              memory: 71Mi
            requests:
              cpu: 10m
              memory: 67Mi
          priorityClassName: system-cluster-critical
      storageClass:
        enabled: true
        name: standard-rwx
        isDefault: false
        allowVolumeExpansion: true
        pool: data0
        parameters:
          csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
          csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
          csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
          csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
          csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
  cephFileSystemVolumeSnapshotClass:
    enabled: true
    isDefault: false
  cephObjectStores: []
  ingress:
    dashboard:
      host:
        name: rook-ceph-dashboard
        path: "/"
      tls:
        - hosts:
            - rook-ceph-dashboard
      ingressClassName: tailscale
      annotations:
        tailscale.com/proxy-group: ingress-proxies
  toolbox:
    enabled: true
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: "2m"
        memory: "10Mi"
