dex:
  config:
    issuer: https://dex.west-beta.ts.net
    storage:
      type: kubernetes
      config:
        inCluster: true
    oauth2:
      skipApprovalScreen: true
    connectors:
      - type: oidc
        id: kanidm
        name: Kanidm
        config:
          clientID: $KANIDM_CLIENT_ID
          clientSecret: $KANIDM_CLIENT_SECRET
          redirectURI: https://dex.west-beta.ts.net/callback
          issuer: https://auth.west-beta.ts.net/oauth2/openid/dex
          # TODO https://github.com/dexidp/dex/pull/3188
          # enablePKCE: true
          scopes:
            - openid
            - profile
            - email
            - groups
    staticClients:
      - id: grafana-sso
        name: Grafana
        redirectURIs:
          - "https://grafana.west-beta.ts.net/login/generic_oauth"
        secretEnv: GRAFANA_SSO_CLIENT_SECRET
      - id: gitea
        name: Gitea
        redirectURIs:
          - "https://git.west-beta.ts.net/user/oauth2/Dex/callback"
        secretEnv: GITEA_CLIENT_SECRET
  envFrom:
    - secretRef:
        name: dex-secrets
  ingress:
    enabled: true
    className: tailscale
    annotations:
      tailscale.com/experimental-forward-cluster-traffic-via-ingress: "true"
      tailscale.com/proxy-group: ingress-proxies
    hosts:
      - host: &host dex
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - *host
  serviceMonitor:
    enabled: true
