# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.0/charts/other/app-template/values.schema.json
app-template:
  defaultPodOptions:
    enableServiceLinks: true
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/openspeedtest/latest
            tag: latest
            pullPolicy: Always
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true
              spec:
                failureThreshold: 30
                periodSeconds: 5
  service:
    main:
      controller: main
      ports:
        http:
          port: 3000
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: tailscale
      annotations:
        tailscale.com/proxy-group: ingress-proxies
      hosts:
        - host: &host speedtest.west-beta.ts.net
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - hosts:
            - *host
