grafana:
  # Hardcoded password because of ArgoCD's behavior
  # TODO:
  adminPassword: crse4zLTjCrds8PxdOlTRgcs2jh4QP1AgNM350IG
  ingress:
    enabled: true
    annotations:
      tailscale.com/proxy-group: ingress-proxies
    ingressClassName: tailscale
    hosts:
      - &host grafana
    tls:
      - hosts:
          - *host
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: monitoring-system
    datasources:
      enabled: true
      searchNamespace: monitoring-system
    plugins:
      enabled: true
    resources:
      requests:
        memory: 123Mi
      limits:
        memory: 123Mi
  envFromSecret: grafana-secrets
  grafana.ini:
    server:
      root_url: https://grafana.west-beta.ts.net
    auth.generic_oauth:
      enabled: true
      allow_sign_up: true
      auto_assign_org_role: Admin
      name: Dex
      client_id: grafana-sso
      client_secret: $__env{GRAFANA_SSO_CLIENT_SECRET}
      scopes: openid profile email groups
      auth_url: https://dex.west-beta.ts.net/auth
      token_url: https://dex.west-beta.ts.net/token
      api_url: https://dex.west-beta.ts.net/userinfo
    feature_toggles:
      provisioning: true
      kubernetesClientDashboardsFolders: true
      kubernetesDashboards: true
      grafanaAPIServerEnsureKubectlAccess: true
    rendering:
      server_url: http://grafana-image-renderer:8081/render
      callback_url: http://localhost:3000/
  persistence:
    enabled: true
    size: 1Gi
  useStatefulSet: true
  serviceMonitor:
    enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 254Mi
    limits:
      memory: 512Mi
  imageRenderer:
    enabled: true
