# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.0/charts/other/app-template/values.schema.json
app-template:
  defaultPodOptions:
    enableServiceLinks: true
  controllers:
    main:
      type: statefulset
      replicas: 1
      containers:
        main:
          image:
            repository: docker.io/kanidm/server
            tag: 1.3.3
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true
              spec:
                failureThreshold: 30
                periodSeconds: 5
      statefulset:
        volumeClaimTemplates:
          - name: data
            size: 1Gi
            globalMounts:
              - path: /data
            accessMode: "ReadWriteOnce"
  configMaps:
    config:
      enabled: true
      data:
        server.toml: |
          bindaddress = "[::]:443"
          ldapbindaddress = "[::]:636"
          trust_x_forward_for = true
          db_path = "/data/kanidm.db"
          tls_chain = "/data/ca.crt"
          tls_key = "/data/tls.key"
          domain = "auth.west-beta.ts.net"
          origin = "https://auth.west-beta.ts.net"
  service:
    main:
      controller: main
      ports:
        https:
          port: 443
          protocol: HTTPS
          primary: true
        ldap:
          port: 636
          protocol: TCP
  ingress:
    main:
      enabled: true
      className: tailscale
      annotations:
        tailscale.com/experimental-forward-cluster-traffic-via-ingress: "true"
      hosts:
        - host: &host auth.west-beta.ts.net
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: https
      tls:
        - hosts:
            - *host
  persistence:
    config:
      enabled: true
      type: configMap
      name: kanidm-config
      globalMounts:
        - path: /data/server.toml
          subPath: server.toml
    tls:
      enabled: true
      type: secret
      name: kanidm-selfsigned-certificate
      globalMounts:
        - path: /data/ca.crt
          subPath: ca.crt
        - path: /data/tls.key
          subPath: tls.key
