# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.6.0/charts/other/app-template/values.schema.json
app-template:
  defaultPodOptions:
    enableServiceLinks: true
    hostNetwork: true
  controllers:
    semaphore:
      forceRename: semaphore
      strategy: Recreate
      containers:
        semaphore:
          image:
            repository: semaphoreui/semaphore
            tag: latest
            pullPolicy: Always
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true
              spec:
                failureThreshold: 30
                periodSeconds: 5
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: SEMAPHORE_PORT
              value: ":3000"
            - name: SEMAPHORE_ACCESS_KEY_ENCRYPTION
              value: gs72mPntFATGJs9qK0pQ0rKtfidlexiMjYCH9gWKhTU=
            - name: SEMAPHORE_ADMIN
              value: admin
            - name: SEMAPHORE_DB
              value: semaphore
            - name: SEMAPHORE_DB_DIALECT
              value: mysql
            - name: SEMAPHORE_DB_HOST
              value: semaphore-mysql
            - name: SEMAPHORE_DB_PASS
              value: semaphore
            - name: SEMAPHORE_DB_PORT
              value: "3306"
            - name: SEMAPHORE_DB_USER
              value: semaphore
            - name: SEMAPHORE_PLAYBOOK_PATH
              value: /tmp/semaphore/
            - name: SEMAPHORE_EMAIL_ALERT
              value: "true"
            - name: SEMAPHORE_WEB_ROOT
              value: https://semaphore.west-beta.ts.net
      initContainers:
        chmod-chown-dir:
          image:
            repository: busybox
            tag: latest
          command:
            [
              "sh",
              "-c",
              "chown 1001:0 /tmp/semaphore/ && chmod -v ug+rwx /tmp/semaphore/ && chown 1001:0 /etc/semaphore && chmod -v ug+rwx /etc/semaphore || true",
            ]
    mysql:
      strategy: Recreate
      containers:
        mysql:
          image:
            repository: mysql
            tag: 8.0
          env:
            - name: MYSQL_DATABASE
              value: semaphore
            - name: MYSQL_PASSWORD
              value: semaphore
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "yes"
            - name: MYSQL_USER
              value: semaphore
  service:
    semaphore:
      forceRename: semaphore
      controller: semaphore
      ports:
        http:
          port: 3000
          protocol: TCP
    mysql:
      controller: mysql
      ports:
        mysql:
          port: 3306
          protocol: TCP
  ingress:
    semaphore:
      enabled: true
      className: tailscale
      annotations:
        tailscale.com/proxy-group: ingress-proxies
      hosts:
        - host: &host semaphore
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: semaphore
                port: http
      tls:
        - hosts:
            - *host
  persistence:
    data:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      retain: false
      advancedMounts:
        mysql:
          mysql:
            - path: /var/lib/mysql
    playbook:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 10Gi
      retain: false
      advancedMounts:
        semaphore:
          chmod-chown-dir:
            - path: /tmp/semaphore
          semaphore:
            - path: /tmp/semaphore
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Mi
      retain: false
      advancedMounts:
        semaphore:
          chmod-chown-dir:
            - path: /etc/semaphore
          semaphore:
            - path: /etc/semaphore
